services:
  - type: web
    name: render-uploader-backend
    env: node
    region: oregon
    plan: free
    buildCommand: "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && chmod a+rx /usr/local/bin/yt-dlp && apt-get update && apt-get install -y ffmpeg && npm install"
    startCommand: "node index.js"
    autoDeploy: true
    healthCheckPath: /ping
